[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@pythnetwork/entropy-sdk-solidity/=node_modules/@pythnetwork/entropy-sdk-solidity', 'solmate/=lib/solmate/src/','@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity']

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
hedera= "testnet.hashio.io/api"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
